var rule = {
  title: '红果果短剧',
  host: 'https://www.hongguoguo.tv/',
  url: '/vod/show/id/fyclass/page/fyage.html',
  searchUrl: '/vod/search/page/fypage/wd/**.html',
  class_name: '精选短剧&穿越短剧&古装短剧&逆袭短剧&都市短剧',
  class_url: 'jingxuanduanju&chuanyueduanju&guzhuangduanju&nixiduanju&dushiduanju',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input;\n  }",
  limit: 6,
  double: true,
  推荐: '.cbox_list;*;*;*;*;*',
  一级: '.flex.wrap li;.tim-title&&Text;.lazy&&data-original;.tim-tag&&Text;a&&href',
  二级: {
    title: 'h1.tim-title&&Text',
    img: '.lazy&&data-original',
    desc: '.title-head p&&Text;.play-detail a:eq(3)&&Text;;.play-detail p:eq(3)&&Text;.play-detail p:eq(2)&&Text',
    content: '.play-detail p:eq(5)&&Text',
    tabs: '.swiper-wrapper a',
    lists: '.anthology-list li',
  },
  搜索: '.left li;.tim-title&&Text;.lazy&&data-original;.tim-tag&&Text;a&&href',
}